
kind: Pod
apiVersion: v1 
metadata:
  name: podwithnodeselector
spec:
  nodeSelector: 
    typeofharddisk: ssd
  containers:
  - name: container1 
    image: umarhassanmalik/webapp
    ports: 
    - containerPort: 80

